# Generated by Django 4.0.6 on 2022-08-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.category'),
        ),
    ]
