# Generated by Django 4.0.6 on 2022-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_fooditems_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
