# Generated by Django 4.0.6 on 2022-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_fooditems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
