# Generated by Django 4.0.6 on 2022-08-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_fooditems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='quantity',
        ),
    ]
