# Generated by Django 4.0.6 on 2022-09-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_remove_fooditems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='quantity',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
