# Generated by Django 4.0.6 on 2022-09-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_fooditems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
