# Generated by Django 4.0.6 on 2022-09-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_pass_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
